env = 'MontezumaRevenge-v0'
# env = 'CrazyClimber-v0'
height = 84
width = 84
stacked_frame = 4
skip = 1
gamma = 0.95
lam = 0.98
eps = 0.15
lr = 0.0002
epoch = 4
batch_size = 4
hidden = 512
iter_max = 10000
l2_rate = 0.002
resume = False
actor_path = 'model/atari_' + env
critic_path = 'model/atari_' + env
icm_path = 'model/atari_' + env
actor_name = 'actor1'
critic_name = 'critic1'
icm_name = 'icm1'
horizon = 128
render = False
mario = False
