# env = 'MontezumaRevenge-v0'
# env = 'SuperMarioBros-v0'
# env = 'BreakoutNoFrameskip-v0'
env = 'CrazyClimberNoFrameskip-v0'
# env = 'RiverraidNoFrameskip-v0'
# env = 'SpaceInvadersNoFrameskip-v0'
# env = 'AtlantisNoFrameskip-v0'
height = 84
width = 84
stacked_frame = 4
skip = 1
gamma = 0.95
lam = 0.9
eps = 0.1
lr = 0.00001
epoch = 4
batch_size = 64
hidden = 256
iter_max = 10000
l2_rate = 0.002
ent_coef = 0.01
resume = False
actor_path = 'model/atari/' + env
critic_path = 'model/atari/' + env
icm_path = 'model/atari/' + env
actor_name = 'actor_test'
critic_name = 'critic_test'
icm_name = 'icm1'
horizon = 512
render = False
mario = False
