# env = 'MontezumaRevenge-v0'
# env = 'SuperMarioBros-v0'
# env = 'Breakout-v0'
env = 'CrazyClimberNoFrameskip-v0'
# env = 'RiverraidNoFrameskip-v0'
height = 84
width = 84
stacked_frame = 4
skip = 1
gamma = 0.99
lam = 0.95
eps = 0.1
lr = 0.00025
epoch = 4
batch_size = 32
hidden = 512
iter_max = 10000
l2_rate = 0.002
ent_coef = 0.01
resume = False
actor_path = 'model/atari/' + env
critic_path = 'model/atari/' + env
icm_path = 'model/atari/' + env
actor_name = 'actor0'
critic_name = 'critic0'
icm_name = 'icm1'
horizon = 256
render = False
mario = False
